networks:
  alga-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "FAce1122@@"
      MYSQL_DATABASE: "algafoodapi"
      MYSQL_USER: "delmondes"
      MYSQL_PASSWORD: "FAce1122@@"
    ports:
      - "3306:3306"
    networks:
      - alga-network

  algafood-oauth:
    image: algafood-oauth:1.0
    environment:
      DB_HOST: algafood-mysql
    ports:
      - "8181:8181"
    networks:
      - alga-network
    depends_on:
      - algafood-mysql

  algafood-api:
    image: algafoodapi:1.0
    environment:
      DB_HOST: algafood-mysql
      OAUTH_HOST: algafood-oauth
    ports:
      - "8080:8080"
    networks:
      - alga-network
    depends_on:
      - algafood-mysql
      - algafood-oauth